package com.egouer.admin.auth.domain;

import java.util.Date;

public class Function {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.functionId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Long functionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.functionName
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String functionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.functionCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String functioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.updateTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.status
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.functionUrl
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String functionurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Function.functionType
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String functiontype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.functionId
     *
     * @return the value of Function.functionId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Long getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.functionId
     *
     * @param functionid the value for Function.functionId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setFunctionid(Long functionid) {
        this.functionid = functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.functionName
     *
     * @return the value of Function.functionName
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getFunctionname() {
        return functionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.functionName
     *
     * @param functionname the value for Function.functionName
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setFunctionname(String functionname) {
        this.functionname = functionname == null ? null : functionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.functionCode
     *
     * @return the value of Function.functionCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getFunctioncode() {
        return functioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.functionCode
     *
     * @param functioncode the value for Function.functionCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setFunctioncode(String functioncode) {
        this.functioncode = functioncode == null ? null : functioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.addTime
     *
     * @return the value of Function.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.addTime
     *
     * @param addtime the value for Function.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.updateTime
     *
     * @return the value of Function.updateTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.updateTime
     *
     * @param updatetime the value for Function.updateTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.status
     *
     * @return the value of Function.status
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.status
     *
     * @param status the value for Function.status
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.functionUrl
     *
     * @return the value of Function.functionUrl
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getFunctionurl() {
        return functionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.functionUrl
     *
     * @param functionurl the value for Function.functionUrl
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setFunctionurl(String functionurl) {
        this.functionurl = functionurl == null ? null : functionurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Function.functionType
     *
     * @return the value of Function.functionType
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getFunctiontype() {
        return functiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Function.functionType
     *
     * @param functiontype the value for Function.functionType
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setFunctiontype(String functiontype) {
        this.functiontype = functiontype == null ? null : functiontype.trim();
    }
}