package com.egouer.admin.auth.domain;

import java.util.Date;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.menuId
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private Long menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.menuName
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.orderNum
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.status
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.addTime
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.updateTime
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.menuCode
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private String menucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.menuType
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private String menutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.supMenuCode
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private String supmenucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Menu.menuUrl
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    private String menuurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.menuId
     *
     * @return the value of Menu.menuId
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.menuId
     *
     * @param menuid the value for Menu.menuId
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.menuName
     *
     * @return the value of Menu.menuName
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.menuName
     *
     * @param menuname the value for Menu.menuName
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.orderNum
     *
     * @return the value of Menu.orderNum
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.orderNum
     *
     * @param ordernum the value for Menu.orderNum
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.status
     *
     * @return the value of Menu.status
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.status
     *
     * @param status the value for Menu.status
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.addTime
     *
     * @return the value of Menu.addTime
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.addTime
     *
     * @param addtime the value for Menu.addTime
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.updateTime
     *
     * @return the value of Menu.updateTime
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.updateTime
     *
     * @param updatetime the value for Menu.updateTime
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.menuCode
     *
     * @return the value of Menu.menuCode
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.menuCode
     *
     * @param menucode the value for Menu.menuCode
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.menuType
     *
     * @return the value of Menu.menuType
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public String getMenutype() {
        return menutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.menuType
     *
     * @param menutype the value for Menu.menuType
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setMenutype(String menutype) {
        this.menutype = menutype == null ? null : menutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.supMenuCode
     *
     * @return the value of Menu.supMenuCode
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public String getSupmenucode() {
        return supmenucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.supMenuCode
     *
     * @param supmenucode the value for Menu.supMenuCode
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setSupmenucode(String supmenucode) {
        this.supmenucode = supmenucode == null ? null : supmenucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Menu.menuUrl
     *
     * @return the value of Menu.menuUrl
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Menu.menuUrl
     *
     * @param menuurl the value for Menu.menuUrl
     *
     * @mbggenerated Mon Apr 18 21:30:02 CST 2016
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }
}