package com.egouer.admin.auth.domain;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.roleId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.roleName
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.updateTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.status
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Role.roleCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String rolecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.roleId
     *
     * @return the value of Role.roleId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.roleId
     *
     * @param roleid the value for Role.roleId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.roleName
     *
     * @return the value of Role.roleName
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.roleName
     *
     * @param rolename the value for Role.roleName
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.addTime
     *
     * @return the value of Role.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.addTime
     *
     * @param addtime the value for Role.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.updateTime
     *
     * @return the value of Role.updateTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.updateTime
     *
     * @param updatetime the value for Role.updateTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.status
     *
     * @return the value of Role.status
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.status
     *
     * @param status the value for Role.status
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Role.roleCode
     *
     * @return the value of Role.roleCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Role.roleCode
     *
     * @param rolecode the value for Role.roleCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }
}