package com.egouer.admin.auth.domain;

import java.util.Date;

public class RoleFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleFunction.roleFunctionId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Long rolefunctionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleFunction.roleCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleFunction.functionCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private String functioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleFunction.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleFunction.roleFunctionId
     *
     * @return the value of RoleFunction.roleFunctionId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Long getRolefunctionid() {
        return rolefunctionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleFunction.roleFunctionId
     *
     * @param rolefunctionid the value for RoleFunction.roleFunctionId
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setRolefunctionid(Long rolefunctionid) {
        this.rolefunctionid = rolefunctionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleFunction.roleCode
     *
     * @return the value of RoleFunction.roleCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleFunction.roleCode
     *
     * @param rolecode the value for RoleFunction.roleCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleFunction.functionCode
     *
     * @return the value of RoleFunction.functionCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public String getFunctioncode() {
        return functioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleFunction.functionCode
     *
     * @param functioncode the value for RoleFunction.functionCode
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setFunctioncode(String functioncode) {
        this.functioncode = functioncode == null ? null : functioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleFunction.addTime
     *
     * @return the value of RoleFunction.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleFunction.addTime
     *
     * @param addtime the value for RoleFunction.addTime
     *
     * @mbggenerated Mon Apr 18 19:45:20 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}