package com.egouer.admin.auth.domain;

import java.util.Date;

import com.egouer.admin.base.BaseObj;

public class User extends BaseObj{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.userId
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.userName
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.status
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.addTime
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.updateTime
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.userId
     *
     * @return the value of User.userId
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.userId
     *
     * @param userid the value for User.userId
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.userName
     *
     * @return the value of User.userName
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.userName
     *
     * @param username the value for User.userName
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.status
     *
     * @return the value of User.status
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.status
     *
     * @param status the value for User.status
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.addTime
     *
     * @return the value of User.addTime
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.addTime
     *
     * @param addtime the value for User.addTime
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.updateTime
     *
     * @return the value of User.updateTime
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.updateTime
     *
     * @param updatetime the value for User.updateTime
     *
     * @mbggenerated Sun Apr 17 01:16:28 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}